export enum Page {
    HOME = 'HOME',
    SUBMIT_VIDEO = 'SUBMIT_VIDEO',
    SUBMIT_IMAGE = 'SUBMIT_IMAGE'
}

export enum State {
    FILE_SELECTING = 'FILE_SELECTING',
    FILE_SELECTED = 'FILE_SELECTED',
    FILE_UPLOADING = 'FILE_UPLOADING',
    FILE_UPLOADED = 'FILE_UPLOADED'
}